spring.application.name=ecommerceApi

# Read MongoDB URI from environment variable MONGODB_URI
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:ecommerceDb}

# Read JWT Secret from environment variable JWT_SECRET
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}