package com.guvi.ecommerceApi.DTO;

import com.guvi.ecommerceApi.Entity.OrderStatus;
import lombok.Data;

import java.math.BigDecimal;
import java.util.List;

@Data
public class OrderResponseDTO {
    private String orderId;       // generated by DB
    private String userId;        // from authenticated user
    private List<OrderItemDTO> items; // snapshot of purchased items
    private BigDecimal totalAmount;   // calculated by backend
    private OrderStatus status;
}
